### ISSUE TITLE
Getting net.spy.memcached.internal.CheckedOperationTimeoutException: Operation timed out. - failing node:

### ISSUE THREAD

**Issue by saichandernagamalla** [onshape/memcached-jcache#3]
Hi @gburd,

We are using memcached-jcache for connecting to a memcache server. When there is peak load to our application, we are seeing timeout exceptions like below:
`java.util.concurrent.CompletionException: javax.cache.CacheException: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: net.spy.memcached.internal.CheckedOperationTimeoutException: Operation timed out. - failing node: ip-10-0-254-72.ap-northeast-1.compute.internal/10.0.254.72:11211
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_232]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_232]
	at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:888) ~[?:1.8.0_232]
	at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:866) ~[?:1.8.0_232]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_232]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) ~[?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]`

We are suspecting, it is due to one client has a single connection to memcache server, and this may be causing the operations to timeout waiting for previous ops to complete.
Is there a way to fix this issue by having connection pooling mechanism.
If yes, does memcached-jcache has such support for connection pooling?

Thanks in advance.

**Comment by gburd** [comment]
Hey @saichandernagamalla thanks for using this library, I made this while at Onshape years ago for use there.  It's been years since I looked into this code, I don't think I have any good ideas for you on this issue.  If you have a PR to review with some fix, I'm happy to review/merge it.
